version: "3.9"
services:
  www:
    build: ./www
    ports:
      - "8080:8080"
  api:
    build: ./api
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mydatabase
      DB_USER: myuser
      DB_PASSWORD: mypassword
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
